### ISSUE TITLE
Missing edges

### ISSUE THREAD

**Issue by sjakobi** [yav/graphmod#9] opened 2016-02-18 21:29 UTC
```
$ git clone https://github.com/commercialhaskell/stack
$ cd stack
$ git checkout 3f7b50fe598ec83eda5d393fe5b08a99ce5ac1e9
$ graphmod src/Stack/Docker.hs src/Stack/Docker/GlobalDB.hs | xdot -
```

There should be an edge from `Stack.Docker` to `Stack.Docker.GlobalDB` but it's missing.

In fact, when running `graphmod src/Stack**.hs | xdot -` there are no edges beginning at `Stack.Docker` at all.

```
$ graphmod -v
graphmod 1.2.8
```

**Comment by yav** [comment] 2016-02-18 21:41
This probably happens because `Stack.Docker` has a package-qualified import that graph-mod does not know about yet. See issue #1.  I really should implement this.  I'll close this ticket for now, as it seems to be a duplicate of #1, please re-open it if you think that there's something else going on.

**Closed by yav** 2016-02-18 21:41 UTC

**Comment by yav** [comment] 2016-02-18 22:17
Hi,

I just pushed a fix to git-hub, which solves the problem of package imports, and then the edges appear correctly.  By the way, the `--prune-edges` flag is often quite useful when looking at large projects such as stack.

Thanks for the report, and let me know how if you encounter other problems.

**Comment by sjakobi** [comment] 2016-02-18 22:33
> I just pushed a fix to git-hub, which solves the problem of package imports, and then the edges appear correctly.

Thanks for the quick fix!

What surprised me, was that when I run `graphmod src/Stack/Docker.hs src/Stack/Docker/GlobalDB.hs | xdot -` now, the graph for the entire package appears, whereas previously it would only show `Stack.Docker` and `Stack.Docker.GlobalDB`. Is this intended?

**Comment by yav** [comment] 2016-02-18 22:52
Ah yeah, that's another new feature, as of 2 days ago :-)   I just added support for Cabal, so by default `graphmod` will look for a `.cabal` file in the current directly, and if it finds one, it will add all the modules and paths from it.

You may use `--no-cabal` to disable this.

In general, the modules given to `graphmod` are treated as "roots" for the graph, and then it will display any other modules it can find in the given paths.   So if you run your example with `--no-cabal` you should see just the two modules, as all other modules are in `src`, and `graphmod` does not know that it should look there.   If you also added `-isrc` in addition to `--no-cabal`, then you'd see the whole graph again, because now it will also search in `src` for files.

Hopefully this makes sense!

**Comment by sjakobi** [comment] 2016-02-18 22:56
Thanks for the clarification and the great tool! :+1:
